name: google-dp-evaluation

on:
  push:
    paths:
      - 'google-dp/evaluation/**'
      - .github/workflows/google-dp-evaluation.yml
      - 'google-dp/src/**'
      - 'dpevaluation/**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          google-dp/evaluation/build.sh
          echo ${{ secrets.PAT }} | docker login ghcr.io -u anthager --password-stdin
          docker push ghcr.io/anthager/google-dp-evaluation
