name: google-dp-postgres

on:
  push:
    paths:
      - 'google-dp/postgres/**'
      - .github/workflows/google-dp-postgres.yml

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          google-dp/postgres/build.sh
          echo ${{ secrets.PAT }} | docker login ghcr.io -u anthager --password-stdin
          docker push ghcr.io/anthager/google-dp-postgres
